#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
#xmodmap "/home/d0d/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec xscreensaver -nosplash &

exec gnome-keyring-daemon --start --daemonize --components=keyring &

exec setxkbmap -layout es -model geniuscomfy &

ck-launch-session fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/d0d/.fluxbox/log"
